### ISSUE TITLE
Can't click on 'HELP' & 'Settings'

### ISSUE THREAD

**Issue by samidadi** [Swirt/typertools-src#17]
This area doesn't seem to be working when the window is in max extension (there is no hand).
![image](https://user-images.githubusercontent.com/13510809/132948652-8dc0b9a0-d8b6-476c-babd-8f99244cb121.png)
 On the contrary, the hand shows up in this case.
![image](https://user-images.githubusercontent.com/13510809/132948734-095e2794-5a28-4cd7-9121-2ba1c7c081c1.png)

**Comment by Swirt** [comment]
Hmm, strange. I was not able to recreate the problem.  
Does it work fine if you attach the extension window to the toolbar, like here:
https://youtu.be/QwxG2S_PCMQ?t=14

**Comment by samidadi** [comment]
Actually, it didn't work at the beginning, however, the problem has gone away after a reboot.
