### ISSUE TITLE
I am subscribed to CC and unfortunately installing Typertool does not appear in 2022 photoshop.

### ISSUE THREAD

**Issue by AmethystX-n** [Swirt/typertools-src#25]
Is there a way to fix it, or so? Typertool has been a huge help so far, and it's kinda a bummer I can't use it when I finally got subscribed to it.

**Comment by Swirt** [comment]
I'm not sure what exactly a subscription might have changed...
Did the extension work fine in PS 2022 before? When you launch the installer now, does it complete without errors, with the line "Installation completed"?

**Comment by AmethystX-n** [comment]
I believe that Typertool stopped working on Photoshop 2021 onwards. I tried downloading 2020's Photoshop(having PS 2020 and 2022 on my PC), and it still doesn't work.

I've attached what comes out when I run it by admin and without. 
![With Admin](https://user-images.githubusercontent.com/69270574/146261614-b5309eec-1e56-4cae-803b-e7854cb4ef5d.png)
![Wtihout Admin](https://user-images.githubusercontent.com/69270574/146261618-520e8070-7107-4981-b7a2-be7487d94976.png)

**Comment by Swirt** [comment]
What version of Windows do you have? For some reason the standard command 'xcopy' doesn't work for you. 
But you can just manually copy the '_app_', '_CSXS_', '_icons_', '_locale_' folders from the extension archive to `C:\Users\*username*\AppData\Roaming\Adobe\CEP\extensions\typertools`
That should help.

**Comment by AmethystX-n** [comment]
Ahh I see, thank you!
