### ISSUE TITLE
License

### ISSUE THREAD

**Issue by milleniumbug** [Swirt/typertools-src#54]
What license does this project have?

**Comment by papjul** [comment]
GitHub docs:
“without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.”
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license

A free and open source license would be appreciated.
See https://choosealicense.com/ if you need help

**Comment by Swirt** [comment]
Thanks for the heads up, but I really don't care. Maybe someone can do it better than me.
Besides, it doesn't make sense since the extension is now deprecated and should be completely rewritten to match newer versions of Photoshop (UXP).

**Comment by papjul** [comment]
> it doesn't make sense since the extension is now deprecated and should be completely rewritten to match newer versions of Photoshop (UXP).

This is actually a reason to consider it. Someone who would like to be your successor would be unable to reuse any of your code, including translations that were provided by outside contributors for no compensation.

If you don't care about free and open source, please at least consider one of the most permissive license so anyone can at least reuse some parts of your code, while crediting you for your original work.

**Comment by Swirt** [comment]
I added the MIT license with the latest update.
